quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:default
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.datasource.dev-ui.allow-sql=true
quarkus.hibernate-orm.log.sql=true
